services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME}
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: ./whitemebel
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG:-0}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-*}
      DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS:-}
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432


      EMAIL_FORCE_IPV4: "0"
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      ORDER_NOTIFY_EMAILS: ${ORDER_NOTIFY_EMAILS}
      CLOUDPAYMENTS_PUBLIC_ID: ${CLOUDPAYMENTS_PUBLIC_ID}
      CLOUDPAYMENTS_API_SECRET: ${CLOUDPAYMENTS_API_SECRET}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
    extra_hosts:
      - "smtp.yandex.ru:77.88.21.158"

      
  nuxt:
    container_name: nuxt-app
    build: ./krim-shop
    # наружу порт не пробрасываем — идём через nginx
    # ports:
    #   - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    # для продакшна обычно МАУНТЫ НЕ НУЖНЫ.
    # если правда надо — оставь, но лучше собрать образ без них:
    # volumes:
    #   - .:/app
    # #   - /app/node_modules
    # ports:
    #   - "3000:3000"

  nginx:
    image: nginx:alpine
    depends_on:
      - web
      - nuxt
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/static:ro
      - media_data:/media:ro

volumes:
  pg_data:
    name: whitemebel_pg_data
  static_data:
  media_data:
