# Generated by Django 5.2.4 on 2025-08-10 21:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mainslider_alter_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фикс')], default='percent', max_length=10, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Величина скидки')),
                ('min_order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Мин. сумма заказа')),
                ('active_from', models.DateTimeField(blank=True, null=True, verbose_name='Активна с')),
                ('active_to', models.DateTimeField(blank=True, null=True, verbose_name='Активна по')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Скидка на доставку',
                'verbose_name_plural': 'Скидки на доставку',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Регион')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Базовая стоимость доставки')),
                ('free_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Порог бесплатной доставки')),
                ('delivery_days_min', models.PositiveSmallIntegerField(default=1, verbose_name='Срок (мин, дней)')),
                ('delivery_days_max', models.PositiveSmallIntegerField(default=3, verbose_name='Срок (макс, дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Регион доставки',
                'verbose_name_plural': 'Регионы доставки',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.productattribute')),
            ],
            options={
                'verbose_name': 'Опция характеристики',
                'verbose_name_plural': 'Опции характеристик',
                'ordering': ['attribute__name', 'value'],
            },
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.attributeoption'),
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together={('product', 'attribute', 'option')},
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['product', 'attribute'], name='core_produc_product_a8835f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryregion',
            index=models.Index(fields=['slug'], name='core_delive_slug_baf5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryregion',
            index=models.Index(fields=['is_active'], name='core_delive_is_acti_273126_idx'),
        ),
        migrations.AddField(
            model_name='deliverydiscount',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.deliveryregion', verbose_name='Регион (пусто = глобальная)'),
        ),
        migrations.AlterUniqueTogether(
            name='attributeoption',
            unique_together={('attribute', 'value')},
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value',
        ),
        migrations.AddIndex(
            model_name='deliverydiscount',
            index=models.Index(fields=['is_active'], name='core_delive_is_acti_9a941c_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverydiscount',
            index=models.Index(fields=['active_from', 'active_to'], name='core_delive_active__71b94e_idx'),
        ),
    ]
