# Generated by Django 5.2.4 on 2025-08-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deliverydiscount_deliveryregion_attributeoption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ('filter_order', 'name'), 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AddField(
            model_name='productattribute',
            name='filter_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок в фильтре'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='filter_widget',
            field=models.CharField(choices=[('select', 'Выпадающий список'), ('checkbox', 'Чекбоксы'), ('radio', 'Радио-кнопки'), ('chips', 'Чипсы/тэги'), ('swatch', 'Сэмплы цвета'), ('slider', 'Слайдер (число)'), ('range', 'Диапазон (число)')], default='checkbox', max_length=16, verbose_name='Стиль фильтра'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_multiselect',
            field=models.BooleanField(default=True, verbose_name='Мультивыбор'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='show_in_filter',
            field=models.BooleanField(default=True, verbose_name='Показывать в фильтре'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название характеристики'),
        ),
    ]
