# Generated by Django 5.2.4 on 2025-08-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг'),
        ),
    ]
