# Generated by Django 5.2.4 on 2025-08-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productattribute_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='show_on_home',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Показывать на главной'),
        ),
    ]
