# Generated by Django 5.2.4 on 2025-09-29 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('authorized', 'Заблокирован'), ('failed', 'Ошибка'), ('refunded', 'Возврат'), ('canceled', 'Отменён')], default='new', max_length=16)),
                ('transaction_id', models.CharField(blank=True, max_length=64)),
                ('invoice_id', models.CharField(blank=True, max_length=64)),
                ('account_id', models.CharField(blank=True, max_length=190)),
                ('card_first_six', models.CharField(blank=True, max_length=6)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('card_type', models.CharField(blank=True, max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'indexes': [models.Index(fields=['invoice_id'], name='core_paymen_invoice_23d2a5_idx'), models.Index(fields=['transaction_id'], name='core_paymen_transac_e8c2f7_idx'), models.Index(fields=['status'], name='core_paymen_status_8390cc_idx')],
            },
        ),
    ]
