# Generated by Django 5.2.4 on 2025-10-02 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneClickRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(db_index=True, max_length=16, verbose_name='Телефон')),
                ('product_url', models.URLField(max_length=500, verbose_name='Ссылка на товар')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('ordered', 'Оформлен заказ'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заявка «в один клик»',
                'verbose_name_plural': 'Заявки «в один клик»',
                'ordering': ('-created_at',),
            },
        ),
    ]
